Repository mojohaus/buildplan-maven-plugin, pull requests merged in 2022-07, with the labels that each got.

#120 Reports code coverage on PR
  .github/workflows/maven.yml
Labels: chore

#121 Use Maven 3.8.6
  .mvn/wrapper/maven-wrapper.properties
Labels: dependencies

#118 Reorder table columns order for list goal
  src/it/list-multimodule-cli-task/expected.txt
  src/it/list-multimodule-cli-task/module-a/expected.txt
  src/it/list-multimodule-cli-task/module-b/expected.txt
  src/it/list-multimodule-outputfile/expected.txt
  src/it/list-multimodule-outputfile/module-a/expected.txt
  src/it/list-multimodule-outputfile/module-b/expected.txt
  src/it/list-multimodule-single-outputfile/expected.txt
  src/it/list-multimodule-with-lifecycle/expected.txt
  src/it/list-multimodule-with-lifecycle/module-a/expected.txt
  src/it/list-multimodule-with-lifecycle/module-b/expected.txt
  src/it/list-multimodule/expected.txt
  src/it/list-multimodule/module-a/expected.txt
  src/it/list-multimodule/module-b/expected.txt
  src/main/java/org/codehaus/mojo/buildplan/ListMojo.java
  src/main/java/org/codehaus/mojo/buildplan/display/ListTableDescriptor.java
  src/test/java/org/codehaus/mojo/buildplan/display/ListTableDescriptorTest.java
Labels: feature

#125 Fixed #124 - Cleanup pom file
  pom.xml
Labels: chore

#127 Fixed #126 - Code cleanup / Improvements
  src/main/java/org/codehaus/mojo/buildplan/AbstractLifecycleMojo.java
  src/main/java/org/codehaus/mojo/buildplan/ListMojo.java
  src/main/java/org/codehaus/mojo/buildplan/ListPhaseMojo.java
  src/main/java/org/codehaus/mojo/buildplan/ListPluginMojo.java
  src/main/java/org/codehaus/mojo/buildplan/display/AbstractTableDescriptor.java
  src/main/java/org/codehaus/mojo/buildplan/util/LinkedMultimap.java
Labels: chore

#129 Fixed #128 - Build on JDK11/JDK17 produces warning - Illegal reflecti…
  src/test/java/org/codehaus/mojo/buildplan/GroupsTest.java
Labels: chore

#131 Fixed #130 - Migrate to JUnit Jupiter
  pom.xml
  src/test/java/org/codehaus/mojo/buildplan/GroupsTest.java
  src/test/java/org/codehaus/mojo/buildplan/display/ListPhaseTableDescriptorTest.java
  src/test/java/org/codehaus/mojo/buildplan/display/ListPluginTableDescriptorTest.java
  src/test/java/org/codehaus/mojo/buildplan/display/ListTableDescriptorTest.java
  src/test/java/org/codehaus/mojo/buildplan/display/MojoExecutionDisplayTest.java
Labels: chore

#137 Add a :report goal to generate plugin executions list in HTML
  README.md
  pom.xml
  src/main/java/org/codehaus/mojo/buildplan/ListReportMojo.java
  src/site/markdown/index.md
  src/site/markdown/usage.md.vm
  src/site/resources/images/report-example.png
  src/test/java/org/codehaus/mojo/buildplan/ListReportIT.java
  src/test/resources-its/org/codehaus/mojo/buildplan/ListReportIT/generate_report_for_multimodule_project/module-a/pom.xml
  src/test/resources-its/org/codehaus/mojo/buildplan/ListReportIT/generate_report_for_multimodule_project/module-b/pom.xml
  src/test/resources-its/org/codehaus/mojo/buildplan/ListReportIT/generate_report_for_multimodule_project/pom.xml
Labels: feature

#138 Automatically release on Maven Central
  pom.xml
Labels: chore
