Repository mojohaus/buildplan-maven-plugin, pull requests merged in 2023-01, with the labels that each got.

#160 Fix tests by defining versions-maven-plugin version
  src/test/resources-its/org/codehaus/mojo/buildplan/ListIT/MultiModuleProject/maven_project/pom.xml
Labels: chore

#162 Use Maven 3.8.7
  .mvn/wrapper/maven-wrapper.properties
Labels: dependencies

#159 Do not print ANSI escape codes in site report
  src/main/java/org/codehaus/mojo/buildplan/ReportMojo.java
  src/main/java/org/codehaus/mojo/buildplan/display/MojoExecutionDisplay.java
  src/main/java/org/codehaus/mojo/buildplan/display/PlainTextMojoExecutionDisplay.java
  src/test/java/org/codehaus/mojo/buildplan/ReportIT.java
Labels: bug

#164 Fix broken HTML table in report goal when using maven-site-plugin:4.0.0-M4
  src/main/java/org/codehaus/mojo/buildplan/ReportMojo.java
  src/test/java/org/codehaus/mojo/buildplan/ReportIT.java
  src/test/resources-its/org/codehaus/mojo/buildplan/ReportIT/generate_report_with_mvn_site_plugin_v4/module-a/pom.xml
  src/test/resources-its/org/codehaus/mojo/buildplan/ReportIT/generate_report_with_mvn_site_plugin_v4/module-b/pom.xml
  src/test/resources-its/org/codehaus/mojo/buildplan/ReportIT/generate_report_with_mvn_site_plugin_v4/pom.xml
Labels: bug
